version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    env_file:
      - .env  # Place your DATABASE_URL and SECRET_KEY here
    expose:
      - 8000
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always 