version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: new_gen
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: dwij9143
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # make sure init.sql exists
    restart: always

  web:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
