"""your description

Revision ID: 2b968ed498d6
Revises: f7195268e430
Create Date: 2025-11-06 13:23:39.913954
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b968ed498d6'
down_revision = 'f7195268e430'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_prompts', schema=None) as batch_op:
        batch_op.alter_column('gpt_model',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_prompts', schema=None) as batch_op:
        batch_op.alter_column('gpt_model',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'gpt-4o-mini'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
