"""test

Revision ID: 5bc86fd614bc
Revises: 000000000000
Create Date: 2025-10-13 18:21:51.897273
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc86fd614bc'
down_revision = '000000000000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dynamic_prompts', 'gpt_model',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'gpt-4o-mini'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dynamic_prompts', 'gpt_model',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'gpt-4o-mini'::character varying"))
    # ### end Alembic commands ###
