"""update the chat

Revision ID: f7195268e430
Revises: 5bc86fd614bc
Create Date: 2025-10-28 17:31:03.836469
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7195268e430'
down_revision = '5bc86fd614bc'
branch_labels = 'None'
depends_on = 'None'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynamic_prompts', schema=None) as batch_op:
        batch_op.alter_column('gpt_model',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_prompts', schema=None) as batch_op:
        batch_op.alter_column('gpt_model',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'gpt-4o-mini'::character varying"),
               existing_nullable=True)

    op.drop_table('chat_documents')
    # ### end Alembic commands ###
